name: Build Docker Image
run-name: Build multiplatform Image for Focalboard ${{ inputs.release_tag }}
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Focalboard tag"
        required: true
        default: "v7.11.3"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}
  PLATFORMS: |
    linux/arm64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Get Focalboard Git Repo
        uses: actions/checkout@v4.1.0
        with:
          repository: 'mattermost/focalboard'
          ref: ${{ inputs.release_tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ inputs.release_tag }}
