name: Build Docker Image
run-name: Build arm64 Image for Focalboard ${{ inputs.release_tag }}
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Focalboard tag"
        required: true
        default: "v7.11.3"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/focalboard-arm64
  PLATFORMS: |
    linux/arm64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Get Focalboard Git Repo
        uses: actions/checkout@v4.1.0
        with:
          repository: 'mattermost/focalboard'
          ref: ${{ inputs.release_tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{raw}},value=${{ inputs.release_tag }}
            type=semver,pattern={{version}},value=${{ inputs.release_tag }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.release_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.release_tag }}
      - 
        name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
